apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: coffee-service
spec:
  protocol: "http"
---
# Service to expose coffee-service

apiVersion: v1
kind: Service
metadata:
  name: coffee-service
spec:
  selector:
    app: coffee-service
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: coffee-service
automountServiceAccountToken: true

---
# Coffee Service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-service
  labels:
    app: coffee-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffee-service
  template:
    metadata:
      labels:
        app: coffee-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "postgres:5432"
    spec:
      serviceAccountName: coffee-service
      containers:
        - name: coffee-service
          image: hashicorpdemoapp/coffee-service:v0.0.1
          ports:
            - containerPort: 9090
            - containerPort: 9103
          env:
            - name: "USERNAME"
              value: "postgres"
            - name: "PASSWORD"
              value: "password"
            - name: "LOG_FORMAT"
              value: "text"
            - name: "LOG_LEVEL"
              value: "INFO"
            - name: "BIND_ADDRESS"
              value: "localhost:9090"
            - name: "METRICS_ADDRESS"
              value: "localhost:9103"
            - name: "VERSION"
              value: "v1"
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 30
