global:
  name: consul
  image: hashicorp/consul:1.12.0
  imageEnvoy: envoyproxy/envoy:v1.22.2
  imageK8S: hashicorp/consul-k8s-control-plane:0.44.0
  datacenter: dc1
  acls:
    manageSystemACLs: true
server:
  replicas: 1
  exposeGossipAndRPCPorts: true
  ports:
    serflan:
      port: 9301
client:
  exposeGossipPorts: true
ui:
  enabled: true
connectInject:
  transparentProxy:
    defaultEnabled: true
  # inject an envoy sidecar into every new pod, except for those with annotations that prevent injection
  enabled: true
  centralConfig:
    enabled: true
    # proxyDefaults is a raw json string that will be applied to all Connect
    # proxy sidecar pods that can include any valid configuration for the
    # configured proxy.
    # proxyDefaults: |
    #   {
    #     "envoy_prometheus_bind_addr": "0.0.0.0:9102"
    #   }
controller:
  enabled: true
